



    <div class="block block-banner">
        <div class="sidebar-banner">
            <img src="<?= $this->getViewFileUrl('images/sofort.png') ?>" title="PayPal - VISA" alt="PayPal - VISA">
        </div>
    </div>

    <div class="block block-banner">
        <div class="sidebar-banner">
            <img src="<?= $this->getViewFileUrl('images/austria_ssl.png') ?>" title="Austria - SSL" alt="Austria - SSL">
        </div>
    </div>




