

<div class="footer-images">
    <figure>
        <img src="<?= $this->getViewFileUrl('images/universitat_wien.png') ?>" alt="universitat wien">
    </figure>
    <figure>
        <img src="<?= $this->getViewFileUrl('images/imgw.png') ?>" alt="imgw">
    </figure>
    <figure>
        <img src="<?= $this->getViewFileUrl('images/vera.png') ?>" alt="vera">
    </figure>
    <figure>
        <img src="<?= $this->getViewFileUrl('images/fwf.png') ?>" alt="fwf">
    </figure>
</div>







    