<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Generic.Files.LineLength.TooLong

/** @var \Magento\Contact\Block\ContactForm $block */
/** @var \Magento\Contact\ViewModel\UserDataProvider $viewModel */

$viewModel = $block->getViewModel();
?>
<form class="form contact"
      action="<?= $block->escapeUrl($block->getFormAction()) ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <br />
        <div class="field note no-label">
            <?= $block->escapeHtml(__('Contact Information')) ?>
        </div>
        <div class="form-list">
            <div class="fields">
                <div class="field name required">
                    <label class="label" for="name"><span><?= $block->escapeHtml(__('Name')) ?></span><em>*</em></label>
                    <div class="control">
                        <input name="name"
                            id="name"
                            title="<?= $block->escapeHtmlAttr(__('Name')) ?>"
                            value="<?= $block->escapeHtmlAttr($viewModel->getUserName()) ?>"
                            class="input-text"
                            type="text"
                            data-validate="{required:true}"/>
                    </div>
                </div>
                <div class="field email required">
                    <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span><em>*</em></label>
                    <div class="control">
                        <input name="email"
                            id="email"
                            title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                            value="<?= $block->escapeHtmlAttr($viewModel->getUserEmail()) ?>"
                            class="input-text"
                            type="email"
                            data-validate="{required:true, 'validate-email':true}"/>
                    </div>
                </div>
            </div>
            <div class="field telephone">
                <label class="label" for="telephone"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
                <div class="control">
                    <input name="telephone"
                        id="telephone"
                        title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
                        value="<?= $block->escapeHtmlAttr($viewModel->getUserTelephone()) ?>"
                        class="input-text"
                        type="tel" />
                </div>
            </div>
            <div class="field comment required">
                <label class="label" for="comment">
                    <span><?= $block->escapeHtml(__('What’s on your mind?')) ?></span><em>*</em>
                </label>
                <div class="control">
                    <textarea name="comment"
                            id="comment"
                            title="<?= $block->escapeHtmlAttr(__('What’s on your mind?')) ?>"
                            class="input-text"
                            cols="5"
                            rows="3"
                            data-validate="{required:true}"><?= $block->escapeHtml($viewModel->getUserComment()) ?>
                    </textarea>
                
                </div>
            </div>
            <?= $block->getChildHtml('form.additional.info') ?>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <p class="required">* Required Fields</p>
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "contact-form"
            }
        }
    }
</script>
